name: pyomo-wheel-build
on:
  workflow_dispatch:
jobs:
  my_job:
    name: build-env-and-run
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: 3.11.2
      - run: |
          pip install pyodide-build>=0.23.0
          echo EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version) >> $GITHUB_ENV
      - uses: mymindstorm/setup-emsdk@v14
        with:
           version: ${{ env.EMSCRIPTEN_VERSION }}
      - run: pyodide build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
